### ISSUE TITLE
Darkness prevents to appreciate the landscapes

### ISSUE THREAD

**Issue by ghost** [FaceDeer/dfcaverns#2] opened 2018-04-08 16:54 UTC
The underground biomes are gorgeous, but you can't see them; I've worked around this by simply adding a faint light source to some nodes (previews at page bottom):

```
minetest.override_item("dfcaverns:blood_thorn", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:dirt_with_cave_moss", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:cobble_with_floor_fungus", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:nether_cap", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:black_cap_stem", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:tower_cap", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:spore_tree_hyphae", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:tunnel_tube", {
	light_source = 5,
	}
)

minetest.override_item("dfcaverns:goblin_cap", {
	light_source = 5,
	}
)
```

![red_mushrooms](https://user-images.githubusercontent.com/30574109/38470035-c781e77e-3b5d-11e8-811e-f3470247b43e.jpg)

![bloodthorns](https://user-images.githubusercontent.com/30574109/38470058-ffc4230e-3b5d-11e8-9632-df445b97a3c8.jpg)

![spore_trees](https://user-images.githubusercontent.com/30574109/38470073-2f6c3da8-3b5e-11e8-96fe-88595ebbcb03.jpg)

**Comment by FaceDeer** [comment] 2018-04-08 23:27
Hm... this may be a difference in aesthetics, I deliberately turned down the "glowiness" of the subterranean realms compared to the older caverealms mod because I liked the shadowy mystery of it all. And the darkness was also a bit of a deliberate dirty trick as far as the Bloodthorn caverns was concerned given that Bloodthorns injure you when you bump into them. :)

How about I add some configuration settings to allow the glowyness to be tweaked on a per-game basis? Or maybe add some additional glowing fungus decorations to scatter around more liberally without completely lighting up the ground?

**Comment by H4mlet** [comment] 2018-04-09 11:25
I think that your idea about adding a setting to let the players choose if the glow should be turned on is the best one; in my game players can choose to spawn directly into a cave, given its survival nature it would be a nonsense to start playing into complete darkness, without anything, surrounded by hostile mobs.

Besides this I think it's a matter of tastes. :)

**Comment by H4mlet** [comment] 2018-05-15 21:55
I'm in the process of rebuilding my git repository, however I had noticed the exploding tunnel fruits; I thought that there was some Dungeon Master shooting at me, then I realized that a lava fall had triggered those explosions :D 
I'm not running a server, but I've made a survival medieval subgame "[Hamlet's Quest](https://forum.minetest.net/viewtopic.php?f=15&t=18207)" which features all the Castle ++ mods, plus yours, it even allows to spawn directly underground if one is mad enough to start playing the game from there (hunger, thirst, etc.)
Soon I'll put it on GitHub, however the link above also features a "showcase map" where I've built a small fort which uses your drawbridges, etc.

**Comment by FaceDeer** [comment] 2018-05-16 17:30
Whew, you're back. Was concerned when you turned into a ghost. :)

The latest shiny object that has distracted me might also be of interest to you: [the deep_roads mod](https://github.com/FaceDeer/deep_roads). There have been a few mods I've seen that added "mine shafts" and "dungeons" to mapgen, but I've never been terribly satisfied with them because they're usually just localized random squiggles that don't lead anywhere interesting. The Deep Roads mod adds random-but-purposeful _long-range_ tunnels. It operates by pseudo-randomly distributing "intersections" chambers across the map and then determining which ones are connected to each other, then draws corridors between them. The nature of the corridors are highly configurable, they can be broad or narrow, contain rails, have torches or not, or even fake up "sewer tunnels" with water in them.

In the current state of the code I've got most of the tunnel work done (still a few fiddly bits to work on such as alternative torch arrangements), but I have yet to set it up to allow for a diverse variety of tunnels to be used. And the intersections remain as just big empty rooms, I'd like to add a more complicated "dungeon" at those places. Don't use this mod on a production server yet because the tunnel arrangement will change with most commits I make at this point.

As for the dfcaverns mod and its lighting issues, still nothing major on that front. I experimented with adding a globs of glowing "mese water" to the Sunless Sea but I'm not happy with the result. Had an idea for glowing kelp but the new waterplant drawtype is too limited for what I had in mind. I'll probably take another crack at this before I get into dungeon generation for Deep Roads, I am feeling rather burnt out on intricate mapgen thinking right now (though I learned a lot in the process).

**Comment by FaceDeer** [comment] 2018-05-19 22:35
Added some giant glowing red crystals to the lower, dryer caves. These are caves that don't have glow worms hanging from the ceilings so they're generally just black.

Also added some big mese crystal formations to the roof of the lava sea, to reward players who risk digging around down there. :)

In a related mod, I added hot cobble and glowing obsidian to the magma_conduits mod to provide a bit of warning that you're about to dig into a seam of magma. I mention it here because it's Dwarf Fortressy. I'm considering redoing the magma conduits to make use of the column-making code I added to subterrane a while back, that should allow me to construct cinder cones on the surface. Not a high priority, though.

**Comment by H4mlet** [comment] 2018-05-23 22:09
Magma conduits? I must check that; I was thinking about adding "hot air" nodes around magma sources, since in real life one can't walk nearby lava without being burnt. But that would probably mean node timers or abms - lag. Anyway. So many mods to try and check!

**Comment by FaceDeer** [comment] 2018-05-23 22:51
Heh, I've been pondering how to damage the player when they're near certain nodes for other reasons - I just added some new decorative stuff to the Sunless Sea biomes (there's now three different biomes in the Sunless Sea) and one of them is a kelp-like plant I call "snareweed" that looks nasty and should probably hurt to swim through. But since it's using the new plantlike_rooted drawtype, the place where the plant appears to be is not actually inside the snareweed node.

Once I figure out how to do that 'cheaply' I'll look at generalizing it to lava. Might make a good stand-alone mod.

**Comment by FaceDeer** [comment] 2018-05-24 09:18
Grumble mumble it's 3:00 AM and you gave me the itch to start a new mod. :)

Check out this: https://github.com/FaceDeer/radiant_damage

It's a mod I just put together that should, in theory, be a nice cheap way of implementing radiant damage for lava (as well as damage for snareweed, though I haven't tried that part out yet). It registers a globalstep callback that triggers once per second to check if there are any lava nodes near each player, and if it finds lava nodes within range it runs some raycasts to determine whether the player has line of sight to them. It totals up the damage from each "visible" lava node, accounting for the inverse square falloff of radiant heat, and then hits the player with it. No abms or node timers necessary, and if none of the target node types are near the player there's no costly math or raycasting to be done.

The current damage dealt is 10 points if you're standing right next to a single lava node. But since lava generally comes in lots of flowing nodes this can get nasty quickly. I jumped into a large pool and it one-shotted me with 68 points of damage before I even got submerged. :) Realistic, but maybe needs tweaking for game balance, we'll see. I haven't played around with it much, just confirmed that it seems to be working in a sane manner.

When I stumble home from work tomorrow I'll clean this up with some configurable settings.  Maybe make fire a little painful to be standing next to, too. Could even make Mese ore "radioactive", doing a tiny amount of damage if you're right next to it. Bunch of uses for this come to mind.

**Comment by H4mlet** [comment] 2018-05-24 16:49
The whole idea is cool, for it would allow various uses; I'm thinking about an ore that I've made for a fantasy mod, I could use this method to mimic magic effects, e.g. people floating or walking faster when near it (I already imagine high speed tunnels, a sort of natural maglev).
BUT, I've found a showstopper bug (God made me for that you know) here's the [log](https://gist.github.com/H4mlet/657773202a6cdaeb593733acd7f9e33f)

**Comment by FaceDeer** [comment] 2018-05-24 17:47
Oh, fooey. The raycast API appears to have been added for Minetest version 0.5, it's not in the api documentation for version 0.4.16. There's a "line of sight" test available in 0.4.16 but I chose not to use that because it counts objects (such as the player) as an obstruction, meaning that testing line of sight from the player's location is always obstructed.

I'll see about adding a check for Raycast's availability into the mod and fall back to using the old line-of-sight test if it's not there (I can do some hackiness to work around the problem of always having the test hit the player). I'm worried that line-of-sight might also ignore liquids, the raycast test ignores liquids by default and I had to explicitly tell it to check that. That would make deep lava too damaging because nodes below the surface layer will be able to damage the player too.

I've been grabbing the latest version 0.5 builds from https://minetest.kitsunemimi.pw/builds/ if you're interested in trying this out before I try adding backward-compatibility.

**Comment by FaceDeer** [comment] 2018-05-24 19:57
Okay, I just updated radiant_damage with basically untested 0.4.16 compatibility over lunch (I just made sure it didn't crash and does hurt the player - didn't check if it's considering liquid to be obstructive or not yet). Seems like whatever problem I was having with line_of_sight supposedly colliding with the player last night was a result of a hazy 3:00 AM brain failure instead, I didn't need to do any hackery to work around that.

This is turning into quite the omnibus "issue" thread, we've addressed three other mods so far I think. :)

**Comment by FaceDeer** [comment] 2018-05-25 03:52
I think I'm just about done this revamp of dfcaverns. I know I haven't made it quite as bright as you requested in your original comment, but I think I've made many of the caverns more "visible" than they were before and if you still need it brighter you can do some of the overrides you mentioned initially.

To summarize the changelog for the sunless_sea branch:

- Created the Sunless Sea, an expansive half-flooded cavern layer between the bottommost "dry" cavern layer and the Lava Sea below that.
- Added three biomes for the Sunless Sea: barren, cave coral, and snareweed. Cave coral and snareweed both have dim light emission to add visibility to the underwater areas. Snareweed is painful if radiant_damage is installed.
- Added new gigantic stalagmite, stalactite, and columnar formations to all cavern levels.
- Reduced flooding in the "wet" cavern biomes. There's still a lot of water sloshing around in some of them, but this should get rid of situations where there's a giant wall of water bisecting a cavern.
- Added "flawless mese blocks" hanging from the ceiling of the lava sea caverns.
- Clusters of large hexagonal glowing red crystals on the ceilings of dry, deep caverns (in particular bloodthorn caverns) to add visibility in some biomes where glow worms don't survive.
- New mesh-based tunnel tube nodes to make them more tubular.
- Extra coal added to black cap caverns, and black cap gills made into excellent raw materials for torch-making - black cap biomes remain pitch black but now there's plenty of supplies for making lots of torches quickly there.
- Added a bit of glow to Nethercap gills. Doesn't do much to illuminate the caverns as a whole, granted, but it looks nice and is visible from a distance.
- Added a soft glow to cave moss, which gives a good view of the shape of the floor in the damper biomes. Floor fungus is the dry-biome carpet vegetation and it remains unlit. Flooded caverns are also still not well lit. I think variety is nice, and some caverns should remain scary yawning chasms of blackness.

I think that's all. If you're still concerned about the survivability of freshly-spawned players in the caverns, I recall seeing a mod once that gives freshly-spawned players a "starting inventory" - perhaps it can be set up to give them a stock of torches and a pick or a weapon each time they spawn down there. 

Can you think of any other things you might like me to tweak or add for the benefit of your game? I need to try it out, I haven't actually experienced DFCaverns with hostile mobs in them before. :)

**Comment by H4mlet** [comment] 2018-05-25 12:06
That's a lot of features, I'm going to test it along with magma conduits and radiant damage.
Regarding the starting inventory, there's no problem: minetest.conf allows doing that.
I can't think of any other features: the whole underground biome is already gorgeous as it is and allows building and farming, so it's perfect.
The only thing that bugs me are lava falls, most of them Niagara-sized, occurring quite frequently and setting everything on fire; but I think that magma-conduits will prevent this issue. :)
If you try my game let me know what you think, the next releases will feature dwarves (to balance hostile mobs) and a few other things (campfire, bedroll, etc.) that should make fresh starts and exploration easier and more interesting (I hope).

**Comment by FaceDeer** [comment] 2018-05-25 12:18
Yeah, mapgen magma proved difficult to get a handle on. I added some code that was supposed to solidify any magma that was genned inside the caverns (or near it) but it seemed that at least some of the mapgen magma gets placed after dfcaverns runs so it didn't always work. The lava-as-ore approach used in magma conduits seems to work more consistently, though it's not perfect - if there's a tunnel that passes through a lava vein into a dfcavern it can provide a path for lava to flow past the obsidian plug.

Also, there's a few cavern biomes where I deliberately omitted the obsidian plugs because the occasional lava-fall is fun. :) Look for the _subterrane_mitigate_lava property on the biome definitions if you want to tweak those.

There are a couple of mods I know of that make cave exploration easier, I'll see if I can put together a list of recommendations later today. No idea how busy my schedule's going to be.

**Comment by H4mlet** [comment] 2018-05-25 19:18
I've been testing the sunless sea branch along with magma conduits and radiant damage.
The crystals are really nice, I was like "Ooooh!" when I saw them first :)
Tunnel tubes are cool, they look just perfect with the new shapes; the old ones looked "fractured", as if not being part of the same structure.
The massive pillars are glorious. They are astounding, making one feel tiny. When you see one emerging from the sea you think "well, _God_ has been busy here". :) You look up and they vanish who knows where, it's really like being in another world.

Visibility is now better, glow worms, crystals and moss, still too dark for my game though; but I'll use overriders, for I think that the mod is perfect as it is and shouldn't be tailored for a specific game - it is realistic right now, it wouldn't be if you applied the changes I've chosen for my game.

Last, the "bad" part: I've experienced massive water floodings, I mean, whole map chunks where everything was covered by flowing water or where huge waterfalls - and I mean stuff like 20x20 nodes , possibly more - were going to submerge everything.
This isn't new for me, I had experienced this with the older versions, but I must say that it's quite bad 'cause you can fly around for 5/10 mins before eventually finding a place that isn't flooded. Go figure if you can just walk. :/

And again, radiant damage crashed the game on a fresh map login, but this time it seems due to a minor bug (brain failures happen!):

> ../mods/radiant_damage/init.lua:102: attempt to perform arithmetic on local 'rounded_pos' (a table value)

Thanks for your work both on the castles mods AND on these mods, my game heavily relies on those and I must say that I appreciate your efforts to quickly improve and fix them despite the fact that I keep spotting glitches here and there!

**Comment by FaceDeer** [comment] 2018-05-25 21:54
I think you're slightly out of date on radiant_damage, I fixed that rounded_pos error [here](https://github.com/FaceDeer/radiant_damage/commit/ef35e899127430d852a167912a1c0de25225f12a). It was there from the first version of radiant_damage but wasn't provoked until I actually used the "above only" feature for the snareweed.

The flooding is semi-intentional, there are cavern layers in Dwarf Fortress that are fully flooded so I stuck a lot of water into the moistest biomes in dfcaverns. And given that the entire cave system is below sea level in Minetest it could be worse. :) However, if you really want to avoid it I'll add a config setting that removes most of the remaining water from those caverns.

Alternately, I made the [airtanks](https://github.com/minetest-mods/airtanks) mod specifically because of the flooded caves in dfcaverns. Not medieval, I know, but maybe the visuals could be swapped with magic orbs of water-breathing or something. :) Cave diving is a very dangerous pursuit in RL, I thought it might be neat to add that sort of danger to parts of Minetest.

**Comment by FaceDeer** [comment] 2018-05-26 06:58
I've added a config option in the "lower seas" section that turns off most of the flooding - I left just one half of one biome down on level 3 still heavily flooded when that option is disabled ("dfcaverns_level3_flooded_biome_lower").

I'm curious, I don't see the [dynamic_liquid](https://github.com/minetest-mods/dynamic_liquid) mod in your game, have you tried it out? It causes liquid nodes to actually move around in a slow but semi-realistic manner, I've found it's fun when dynamically-flowing water and lava is combined with caves. When you accidentally punch a hole in the bottom of the ocean there's actually urgency to seal it up. :)

A simple mod that I made to go well with ropes is the [sounding_line](https://github.com/minetest-mods/sounding_line/) mod. It provides a device to players that allows them to check how far down a hole goes, allowing them to pick out the right length of rope to hang or giving them an idea of whether jumping is a good plan.

The [handholds](https://github.com/Ezhh/handholds) mod is nice for caving, lets you climb walls without having to build elaborate staircases and whatnot. I may need to do something to make it work on flowstone, now that I think of it. It'd be nice to be able to climb those columns.

[breadcrumbs](https://github.com/minetest-mods/breadcrumbs) was also written with cave exploration in mind, it's a specialized type of sign that's useful for keeping track of your path through the twisty caverns of Minetest.

**Comment by H4mlet** [comment] 2018-05-29 19:13
> The flooding is semi-intentional, there are cavern layers in Dwarf Fortress that are fully flooded so I stuck a lot of water into the moistest biomes in dfcaverns. And given that the entire cave system is below sea level in Minetest it could be worse. :) However, if you really want to avoid it I'll add a config setting that removes most of the remaining water from those caverns.

> Alternately, I made the airtanks mod specifically because of the flooded caves in dfcaverns. Not medieval, I know, but maybe the visuals could be swapped with magic orbs of water-breathing or something. :) Cave diving is a very dangerous pursuit in RL, I thought it might be neat to add that sort of danger to parts of Minetest.

Thanks for adding that setting, I agree that flooded caverns make sense for realism's sake, but for my kind of game having huge areas where there's basically just water and stone for hundreds of nodes is a serious issue from the survival point of view and from the memory load point of view - granted that I don't have memory shortages, still I think about people using average/low quality computers, or who may think to set up a server (a medieval themed server would be news).

About the airtanks, yeah they would not be in theme; there IS space for magic however, a component which I have intentionally left untouched because first I want to achieve a satisfying realistic medieval setting (which hopefully will be the next release), and only after that start adding water breathing potions, magic wands and the like.

**Comment by FaceDeer** [comment] 2018-05-30 02:58
Alright, I think I'm ready to merge sunless_sea into master, in that case. Just did a few last-minute touchups, will test them out a bit more tonight, and then merge and announce the new version.

I think I'll close this issue when I do. It's been productive, but we've been using it like a forum thread. :) We can pick up discussion either on the forum itself, or on the other issues that have been raised on related mods.

**Comment by FaceDeer** [comment] 2018-05-30 06:53
I'm delaying the merge to see whether Ezhh takes the [pull request](https://github.com/Ezhh/handholds/pull/8) I sent to add an API to handholds, I figured this was the most extensible and robust way I could add flowstone to the types of rock you can climb.

**Comment by H4mlet** [comment] 2018-05-30 10:26
> I think I'll close this issue when I do. It's been productive, but we've been using it like a forum thread. :) We can pick up discussion either on the forum itself, or on the other issues that have been raised on related mods.

I agree :) I'll start right from now to comment on the related mods ("they" should really add a feedback section to be used like the issues section!)

**Closed** 2018-06-01 02:44 UTC
